/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodexchangelists;

import javax.swing.JOptionPane;
import java.lang.*;

/**
 *
 * @author User
 */
public class JDialog_Add_Patient extends javax.swing.JDialog {

    /**
     * Creates new form JDialog_Add_Patient
     */
    public JDialog_File_Chooser fileChooser;
    public JDialog_FoodExchangeList_Plan felPlan;
    public JFrame_Main_Page login;
    public String height;
    public double weight;
    public double intheight;
    public double dbw;
    public double ter;
    public String pa;
    public double bmi;
    public String fullname;
    public String patientRecordNumber;
    public int gender;
    public String address;
    
    public JDialog_Add_Patient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton_Calculate = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_DBW = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_BMI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_TER = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_RecordNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_fullName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_MobileNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Birthdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Gender = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jTextField_Height = new javax.swing.JTextField();
        jComboBox_height = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextField_Weight = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_PhysicalActivity = new javax.swing.JComboBox();

        jTextField9.setText("jTextField9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Patient Record");
        setBounds(new java.awt.Rectangle(450, 100, 0, 0));
        setIconImage(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(30, 145));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 30, -1, 455));

        jPanel2.setPreferredSize(new java.awt.Dimension(714, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 394, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(402, 50));

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setText("Save and Generate FEL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 485, 394, -1));

        jPanel5.setPreferredSize(new java.awt.Dimension(20, 145));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 455));

        jPanel1.setPreferredSize(new java.awt.Dimension(340, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Calculate.setText("Calculate");
        jButton_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jButton_Calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton_Calculate)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 320, 30));

        jPanel8.setLayout(new java.awt.GridLayout(3, 2));

        jLabel9.setText("Desirable Body Weight");
        jPanel8.add(jLabel9);

        jTextField_DBW.setEditable(false);
        jTextField_DBW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_DBW.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_DBW.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_DBW.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(jTextField_DBW);

        jLabel10.setText("Body Mass Index");
        jPanel8.add(jLabel10);

        jTextField_BMI.setEditable(false);
        jTextField_BMI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_BMI.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_BMI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_BMI.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(jTextField_BMI);

        jLabel11.setText("Total Energy Requirement");
        jPanel8.add(jLabel11);

        jTextField_TER.setEditable(false);
        jTextField_TER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_TER.setForeground(new java.awt.Color(255, 0, 0));
        jTextField_TER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_TER.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(jTextField_TER);

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 52, 260, 80));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 272, 340, 160));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "General Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(396, 526));
        jPanel11.setLayout(new java.awt.GridLayout(9, 2));

        jLabel13.setText("Patient Record Number:");
        jPanel11.add(jLabel13);

        jTextField_RecordNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_RecordNumberActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField_RecordNumber);

        jLabel1.setText("Full Name");
        jPanel11.add(jLabel1);
        jPanel11.add(jTextField_fullName);

        jLabel2.setText("Mobile Number");
        jPanel11.add(jLabel2);
        jPanel11.add(jTextField_MobileNumber);

        jLabel3.setText("Birthdate");
        jPanel11.add(jLabel3);
        jPanel11.add(jTextField_Birthdate);

        jLabel4.setText("Gender");
        jPanel11.add(jLabel4);

        jComboBox_Gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel11.add(jComboBox_Gender);

        jLabel5.setText("Address");
        jPanel11.add(jLabel5);
        jPanel11.add(jTextField_Address);

        jLabel7.setText("Height");
        jPanel11.add(jLabel7);

        jPanel14.setLayout(new java.awt.GridLayout(1, 0));
        jPanel14.add(jTextField_Height);

        jComboBox_height.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cm", "inches", "meter" }));
        jPanel14.add(jComboBox_height);

        jPanel11.add(jPanel14);

        jLabel8.setText("Weight");
        jPanel11.add(jLabel8);

        jPanel15.setLayout(new java.awt.GridLayout(1, 2));
        jPanel15.add(jTextField_Weight);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText(" kilograms");
        jPanel15.add(jLabel12);

        jPanel11.add(jPanel15);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Physical Activity");
        jPanel11.add(jLabel6);

        jComboBox_PhysicalActivity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bed Rest", "Sedentary", "Light", "Moderate", "Active" }));
        jPanel11.add(jComboBox_PhysicalActivity);

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 330, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 344, 455));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String dGender;
       fullname = jTextField_fullName.getText();
       patientRecordNumber = jTextField_RecordNumber.getText();
       gender = jComboBox_Gender.getSelectedIndex();
       address = jTextField_Address.getText();
       if(gender == 0){ dGender = "Male";}
       else{dGender = "Female";}
       
        felPlan = new JDialog_FoodExchangeList_Plan(null, true, 
                patientRecordNumber, fullname,dGender,bmi,dbw,ter);
     
        felPlan.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CalculateActionPerformed
        // TODO add your handling code here:
        height = jTextField_Height.getText();
        weight = Double.parseDouble(jTextField_Weight.getText());
        double newHeight = Double.parseDouble(height);
        if(jComboBox_height.getSelectedItem().toString() == "inches"){intheight = newHeight * 2.54;}
        else{intheight = newHeight;}
        //get bmi
            double meterHeight = intheight/100;
            bmi = Math.ceil(weight / (meterHeight * meterHeight));
        
        //get the dbw
        double tenPerc = (intheight - 100) * .10;
        dbw = Math.ceil((intheight - 100) - tenPerc);
        
        //get the PA for the TER
        pa = jComboBox_PhysicalActivity.getSelectedItem().toString();
        if(pa =="Bed Rest") ter = dbw * 27.5;
        else if(pa == "Sedentary")ter = dbw * 30;
        else if(pa == "Light")ter = dbw * 35;
        else if(pa == "Moderate")ter = dbw * 40;
        else if(pa == "Active")ter = dbw * 45;
        
        //display to textfields
        jTextField_DBW.setText(String.valueOf(dbw)+" kg");
        jTextField_BMI.setText(String.valueOf(bmi));
        jTextField_TER.setText(String.valueOf(ter));
       
        
    }//GEN-LAST:event_jButton_CalculateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField_RecordNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_RecordNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_RecordNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_Add_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_Add_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_Add_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_Add_Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_Add_Patient dialog = new JDialog_Add_Patient(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton_Calculate;
    private javax.swing.JComboBox jComboBox_Gender;
    private javax.swing.JComboBox jComboBox_PhysicalActivity;
    private javax.swing.JComboBox jComboBox_height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_BMI;
    private javax.swing.JTextField jTextField_Birthdate;
    private javax.swing.JTextField jTextField_DBW;
    private javax.swing.JTextField jTextField_Height;
    private javax.swing.JTextField jTextField_MobileNumber;
    private javax.swing.JTextField jTextField_RecordNumber;
    private javax.swing.JTextField jTextField_TER;
    private javax.swing.JTextField jTextField_Weight;
    private javax.swing.JTextField jTextField_fullName;
    // End of variables declaration//GEN-END:variables
}
